# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Integration tests
on: [push]
jobs:
  build:
    name: Integration tests
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: 5.10
    - name: Run tests
      run: make test
