name: Tests
on: [push]
jobs:
  build:
    name: Integration tests / macOS
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10"
      - name: Run tests
        run: make test
